---
title: "Exploration of Implicit Weights in Value Search Estimation."
author: "Florian Stijven"
date: "`r Sys.Date()`"
output: html_document
---

The maximization problem in the value search estimator is equivalent to a 
weighted classification problem. In this document, we explore the distribution
of these weights. 

In the following plots, these weights are plotted for the first 20 imputed data
sets for each outcome. 

```{r, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      fig.width = 10)
library(tidyverse)
library(DynTxRegime)
OTR_value_search_results_files = "OTR analyses/OTR-estimation/VSC/results/OTR_results_"
```


```{r}
weight_plot_function = function(outcome) {
  file_name = paste0(OTR_value_search_results_files, 
                    outcome, 
                    ".rds")
  estimated_regimes = readRDS(file_name) %>%
    filter(imputation == "compatible", X_Imputation_ <= 20) %>%
    rename(regime = OTR_estimated) %>%
    mutate(estimated_value = sapply(X = regime,
                                    FUN = estimator)) %>%
    # Among the multiple runs, we select the run that has the largest estimated
    # value.
    group_by(X_Imputation_, outcome, imputation) %>%
    slice_max(order_by = estimated_value,
              n = 1,
              with_ties = FALSE) %>%
    ungroup() 
  
  
  # Compute psi_0 and psi_1 functions as defined in the book of Tsiatis et al.
  # on p. 102.
  weights_VSE_tbl = estimated_regimes %>%
    rowwise(X_Imputation_) %>%
    summarize(
      outcome_model = list(outcome(regime)$Combined),
      propensity_model = list(propen(regime)),
      data = outcome_model$model %>%
        as_tibble() %>%
        list()
    ) %>%
    reframe(
      tibble(
        Q_0 = predict(
          outcome_model[[1]],
          newdata = data[[1]] %>%
            as_tibble() %>%
            mutate(group_int = 0L)
        ),
        Q_1 = predict(
          outcome_model[[1]],
          newdata = data[[1]] %>%
            as_tibble() %>%
            mutate(group_int = 1L)
        ),
        A = data[[1]]$group_int,
        pi_1 = predict(propensity_model[[1]],
                       type = "response"),
        Y = data[[1]]$YinternalY
      )
    ) %>%
    mutate(
      psi_0_hat = ((1 - A) * Y) / (1 - pi_1) + Q_0 * ((A - pi_1) / (1 - pi_1)),
      psi_1_hat = (A * Y) / pi_1 + Q_1 * ((A - pi_1) / pi_1),
      C_abs = abs(psi_1_hat - psi_0_hat)
    )
  weights_VSE_tbl %>%
    ggplot(aes(x = C_abs)) +
    geom_histogram() +
    ylab("Frequency") +
    facet_wrap("X_Imputation_") +
    ggtitle(
      paste0("Distribution of Implicit Weights for ", outcome)
    )
}
```

```{r}
lapply(
  X = c("cesd", "famfun", "madrs", "vas", "sas"),
  FUN = weight_plot_function
)
```


